In [86]:
import numpy as np

In [87]:
import pandas as  pd
import geopandas as gpd

leer datos tabulares

In [88]:
df_inegi = pd.read_csv("/Users/danielbustillos/Desktop/florerias/datos raw/resultados_ageb_urbana_21_cpv2010.csv")
df_inegi = df_inegi[df_inegi["nom_loc"]=="Total AGEB urbana"]
df_inegi["mun"] = df_inegi["mun"].astype(str).str.zfill(3)
df_inegi.head(6)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,pobmas,...,vph_snbien,vph_radio,vph_tv,vph_refri,vph_lavad,vph_autom,vph_pc,vph_telef,vph_cel,vph_inter
3,21,Puebla,001,Acajete,1,Total AGEB urbana,0118,0,3852,1892,...,31,600,690,357,284,194,53,186,279,39
57,21,Puebla,001,Acajete,1,Total AGEB urbana,0160,0,3503,1701,...,31,511,607,332,212,175,46,176,256,22
99,21,Puebla,001,Acajete,1,Total AGEB urbana,0175,0,2541,1244,...,26,349,420,210,145,96,22,94,136,15
137,21,Puebla,001,Acajete,1,Total AGEB urbana,018A,0,1517,730,...,5,238,293,158,114,75,34,73,125,22
161,21,Puebla,001,Acajete,1,Total AGEB urbana,0194,0,2054,955,...,5,367,421,302,249,152,93,150,258,57
188,21,Puebla,001,Acajete,1,Total AGEB urbana,0207,0,2723,1346,...,18,462,519,305,248,188,76,163,273,55

In [89]:
columnas = ['pobmas',  'pobfem',  'p_0a2',  'p_0a2_m',  'p_0a2_f',  'p_3ymas',  'p_3ymas_m',  'p_3ymas_f',  'p_5ymas',  'p_5ymas_m',  'p_5ymas_f',  'p_12ymas',  'p_12ymas_m',  'p_12ymas_f',  'p_15ymas',  'p_15ymas_m',  'p_15ymas_f',  'p_18ymas',  'p_18ymas_m',  'p_18ymas_f',  'p_3a5',  'p_3a5_m',  'p_3a5_f',  'p_6a11',  'p_6a11_m',  'p_6a11_f',  'p_8a14',  'p_8a14_m',  'p_8a14_f',  'p_12a14',  'p_12a14_m',  'p_12a14_f',  'p_15a17',  'p_15a17_m',  'p_15a17_f',  'p_18a24',  'p_18a24_m',  'p_18a24_f',  'p_15a49_f',  'p_60ymas',  'p_60ymas_m',  'p_60ymas_f',  'pob0_14',  'pob15_64',  'pob65_mas',  'pnacoe_m',  'pnacoe_f',  'pres2005',  'pres2005_m',  'pres2005_f',  'presoe05',  'presoe05_m',  'presoe05_f',  'p3ym_hli',  'p3ym_hli_m',  'p3ym_hli_f',  'p3hlinhe',  'p3hlinhe_m',  'p3hlinhe_f',  'p3hli_he',  'p3hli_he_m',  'p3hli_he_f',  'p5_hli',  'p5_hli_nhe',  'p5_hli_he',  'phog_ind',  'pcon_lim',  'pclim_mot',  'pclim_vis',  'pclim_leng',  'pclim_aud',  'pclim_mot2',  'pclim_men',  'pclim_men2',  'psin_lim',  'p3a5_noa',  'p3a5_noa_m',  'p3a5_noa_f',  'p6a11_noa',  'p6a11_noam',  'p6a11_noaf',  'p12a14noa',  'p12a14noam',  'p12a14noaf',  'p15a17a',  'p15a17a_m',  'p15a17a_f',  'p18a24a',  'p18a24a_m',  'p18a24a_f',  'p8a14an',  'p8a14an_m',  'p8a14an_f',  'p15ym_an',  'p15ym_an_m',  'p15ym_an_f',  'p15ym_se',  'p15ym_se_m',  'p15ym_se_f',  'p15pri_in',  'p15pri_inm',  'p15pri_inf',  'p15pri_co',  'p15pri_com',  'p15pri_cof',  'p15sec_in',  'p15sec_inm',  'p15sec_inf',  'p15sec_co',  'p15sec_com',  'p15sec_cof',  'p18ym_pb',  'p18ym_pb_m',  'p18ym_pb_f',  'graproes',  'graproes_m',  'graproes_f',  'pea',  'pea_m',  'pea_f',  'pe_inac',  'pe_inac_m',  'pe_inac_f',  'pocupada',  'pocupada_m',  'pocupada_f',  'pdesocup',  'pdesocup_m',  'pdesocup_f',  'psinder',  'pder_ss',  'pder_imss',  'pder_iste',  'pder_istee',  'pder_segp',  'p12ym_solt',  'p12ym_casa',  'p12ym_sepa',  'pcatolica',  'pncatolica',  'potras_rel',  'psin_relig',  'tothog',  'hogjef_m',  'hogjef_f',  'pobhog',  'phogjef_m',  'phogjef_f',  'vivtot',  'tvivhab',  'tvivpar',  'vivpar_hab',  'tvivparhab',  'vivpar_des',  'vivpar_ut',  'ocupvivpar',  'prom_ocup',  'pro_ocup_c',  'vph_pisodt',  'vph_pisoti',  'vph_1dor',  'vph_2ymasd',  'vph_1cuart',  'vph_2cuart',  'vph_3ymasc',  'vph_c_elec',  'vph_s_elec',  'vph_aguadv',  'vph_aguafv',  'vph_excsa',  'vph_drenaj',  'vph_nodren',  'vph_c_serv',  'vph_snbien',  'vph_radio',  'vph_tv',  'vph_refri',  'vph_lavad',  'vph_autom',  'vph_pc',  'vph_telef',  'vph_cel',  'vph_inter']

In [92]:
df_inegi = df_inegi.replace('*', 0)
df_inegi = df_inegi.replace(' ', 0)

In [93]:
for cada_columna in columnas:
    df_inegi[cada_columna] = df_inegi[cada_columna].fillna(0).astype(float)

leer directorio en csv

In [94]:
df_agebs = gpd.read_file("/Users/danielbustillos/Desktop/florerias/datos raw/AGEBs/AGEB.shp")
df_agebs = df_agebs.rename(columns={"CVE_AGEB":"ageb",
                                   "CVE_MUN":"mun"})
df_agebs.head()

,OBJECTID,CVEGEO,CVE_ENT,mun,CVE_LOC,ageb,Ambito,Shape_Leng,Shape_Area,Latitud,Longitud,geometry
0,1,010010001216A,01,001,0001,216A,Urbana,1765.767569,180700.346075,21.875881,-102.269338,"POLYGON ((2472175.611 1095222.905, 2472149.898..."
1,2,0100100012649,01,001,0001,2649,Urbana,2474.198300,295272.978527,21.863304,-102.250716,"POLYGON ((2474436.992 1094330.964, 2474423.306..."
2,3,010010001383A,01,001,0001,383A,Urbana,1207.362938,90501.634311,21.842288,-102.263716,"POLYGON ((2472973.672 1091954.736, 2472991.031..."
3,4,010010001287A,01,001,0001,287A,Urbana,3104.951619,391476.891904,21.856655,-102.309243,"POLYGON ((2468473.209 1093564.706, 2468482.070..."
4,5,010010001084A,01,001,0001,084A,Urbana,2315.330539,290380.130146,21.869272,-102.300186,"POLYGON ((2469318.936 1094912.739, 2469386.691..."

---

merge

In [82]:
df_agebs_gb = df_agebs.merge(df_inegi, on=["mun","ageb"], how="left")
df_agebs_gb.shape

(2968, 208)

In [83]:
df_agebs_gb

,OBJECTID,CVEGEO,CVE_ENT,mun,CVE_LOC,ageb,Ambito,Shape_Leng,Shape_Area,Latitud,...,vph_snbien,vph_radio,vph_tv,vph_refri,vph_lavad,vph_autom,vph_pc,vph_telef,vph_cel,vph_inter
0,41170,2100100160264,21,001,0016,0264,Urbana,4997.669236,9.996117e+05,19.050999,...,13.0,255.0,300.0,186.0,123.0,96.0,35.0,115.0,126.0,28.0
1,41171,2100100060353,21,001,0006,0353,Urbana,4454.702596,9.657437e+05,19.060363,...,0.0,54.0,56.0,38.0,32.0,13.0,0.0,5.0,29.0,0.0
2,41172,2100100110298,21,001,0011,0298,Urbana,3829.596443,3.431273e+05,19.019565,...,3.0,58.0,72.0,44.0,37.0,20.0,0.0,15.0,41.0,0.0
3,41173,2100100110512,21,001,0011,0512,Urbana,3677.457745,5.633864e+05,19.021817,...,0.0,71.0,80.0,57.0,42.0,25.0,5.0,29.0,42.0,3.0
4,41174,2100100160457,21,001,0016,0457,Urbana,3213.005195,3.756878e+05,19.052583,...,9.0,173.0,198.0,133.0,106.0,55.0,21.0,87.0,93.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2963,74145,212160018,21,216,None,0018,Rural,24881.130647,1.393945e+07,20.009152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2964,74146,212160037,21,216,None,0037,Rural,14520.269795,4.450594e+06,20.112925,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2965,74147,212170015,21,217,None,0015,Rural,93213.922442,9.525835e+07,18.343567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,74148,212170049,21,217,None,0049,Rural,57740.826416,1.203742e+08,18.418606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2967,74149,212170068,21,217,None,0068,Rural,28524.498271,2.849724e+07,18.349520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_agebs_gb.dtypes

OBJECTID       int64
CVEGEO        object
CVE_ENT       object
mun           object
CVE_LOC       object
              ...
vph_autom    float64
vph_pc       float64
vph_telef    float64
vph_cel      float64
vph_inter    float64
Length: 208, dtype: object

In [85]:
df_agebs_gb.to_file("/Users/danielbustillos/Desktop/florerias/socieconómico/poblacion_edad.shp")